package com.app.delmon.Model

data class Test(
    var `data`: Data? = null,
    var error: Boolean? = null,
    var productList: List<Product?>? = null
) {
    data class Data(
        var active: Int? = null,
        var arProductName: String? = null,
        var basketProductList: List<Int?>? = null,
        var cartId: Int? = null,
        var cartonActive: Int? = null,
        var categoryId: Int? = null,
        var createdAt: String? = null,
        var description: String? = null,
        var enProductName: String? = null,
        var id: Int? = null,
        var image: List<String?>? = null,
        var isBasket: Int? = null,
        var isFavorites: Int? = null,
        var isStock: Int? = null,
        var mostWantedProduct: Int? = null,
        var name: Any? = null,
        var newProduct: Int? = null,
        var noOfPieces: Any? = null,
        var offers: Int? = null,
        var parentId: Int? = null,
        var piecesActive: Int? = null,
        var price: Int? = null,
        var quantity: Int? = null,
        var recipiesId: List<Int?>? = null,
        var recipiesList: List<Recipies?>? = null,
        var relatedProduct: List<RelatedProduct?>? = null,
        var serves: Any? = null,
        var soldType: Int? = null,
        var subDescription: Any? = null,
        var type: String? = null,
        var updatedAt: String? = null,
        var weight: Any? = null
    ) {
        data class Recipies(
            var active: Int? = null,
            var categoryId: Int? = null,
            var createdAt: String? = null,
            var id: Int? = null,
            var ingredients: String? = null,
            var name: String? = null,
            var steps: String? = null,
            var thumbnailImage: String? = null,
            var updatedAt: String? = null,
            var videos: String? = null
        )

        data class RelatedProduct(
            var active: Int? = null,
            var arProductName: String? = null,
            var basketProductList: Any? = null,
            var cartonActive: Int? = null,
            var categoryId: Int? = null,
            var createdAt: String? = null,
            var description: String? = null,
            var enProductName: String? = null,
            var id: Int? = null,
            var image: List<String?>? = null,
            var isBasket: Int? = null,
            var isFavorites: Int? = null,
            var isStock: Int? = null,
            var mostWantedProduct: Int? = null,
            var name: Any? = null,
            var newProduct: Int? = null,
            var noOfPieces: Any? = null,
            var offers: Int? = null,
            var parentId: Int? = null,
            var piecesActive: Int? = null,
            var price: Int? = null,
            var recipiesId: List<Int?>? = null,
            var serves: Any? = null,
            var soldType: Int? = null,
            var subDescription: Any? = null,
            var type: String? = null,
            var updatedAt: String? = null,
            var weight: Any? = null
        )
    }

    data class Product(
        var active: Int? = null,
        var arProductName: String? = null,
        var basketProductList: Any? = null,
        var cartonActive: Int? = null,
        var categoryId: Int? = null,
        var createdAt: String? = null,
        var description: String? = null,
        var enProductName: String? = null,
        var id: Int? = null,
        var image: List<String?>? = null,
        var isBasket: Int? = null,
        var isFavorites: Int? = null,
        var isStock: Int? = null,
        var mostWantedProduct: Int? = null,
        var name: Any? = null,
        var newProduct: Int? = null,
        var noOfPieces: Any? = null,
        var offers: Int? = null,
        var parentId: Int? = null,
        var piecesActive: Int? = null,
        var price: Int? = null,
        var recipiesId: List<Int?>? = null,
        var serves: Any? = null,
        var soldType: Int? = null,
        var subDescription: Any? = null,
        var type: String? = null,
        var updatedAt: String? = null,
        var weight: Any? = null
    )
}